### ISSUE TITLE
Usage with Kafka to produce messages

### ISSUE THREAD

**Issue by rsmidt** [beam-community/avro_ex#96]
First of all, thanks for providing a great library! I guess my question does not really fall in to the "issue" category, but after researching for hours, I can't seem to find an end.

I basically want to encode some message and then send via KafkaEx. On the consumer side is a JVM application using the official Kafka/Avro libraries, especially the deserializer. Whenever it tries to deserialize a message sent via the aforementioned setup, it fails, complaining about an unknown magic byte.

My suspicion is that I'm missing another step in the message protocol to make the messages actually deserializable on the other end.

Do you by any chance have a clue of what I'm missing, and how to eventually resolve this?

**Comment by davydog187** [comment]
Hello @rsmidt, it's been a while since I've worked with Kafka, so I personally don't have any suggestions based on what you said. With that being said, if you can provide error messages, a schema, and any other information, I can try to help.

Closing as this isn't a AvroEx unless we discover that there's a bug
